language: ruby
rvm:
  - 1.8.7
  - 1.9.3
gemfile:
  - gemfiles/default-with-activesupport.gemfile
  - gemfiles/json.gemfile
  - gemfiles/yajl.gemfile

env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

